services:
  postgres:
    container_name: portfolio-postgres
    image: postgres:17.5-alpine
    env_file:
      - .env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sveltekit:
    container_name: portfolio-sveltekit
    build:
      context: ./sveltekit
      dockerfile: Dockerfile.dev
    env_file:
      - .env.prisma
      - .env.sveltekit
    volumes:
      - ./sveltekit:/app
      - /app/node_modules
      - uploads:/app/static/uploads
    ports:
      - '5173:5173'
    depends_on:
      - postgres

  passkey:
    container_name: portfolio-passkey
    profiles:
      - passkey
    build:
      context: ./passkey
      dockerfile: Dockerfile
    env_file:
      - .env.prisma
    ports:
      - "127.0.0.1:8080:8080"

volumes:
  postgres_data:
    name: portfolio-postgres_data
  uploads:
    name: portfolio-uploads
