FROM node:24.2-alpine
WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma/
COPY svelte.config.js vite.config.js* vite.config.ts* ./

RUN npm install
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
